# Perfil para Catal√°n
project:
  output-dir: _site/ca

metadata-files:
  - _i18n/ca.yml

format:
  html:
    lang: ca

website:
  title: "Seminari d'Estudiants de Matem√†tiques UB"
  navbar:
    left:
      - href: index.qmd
        text: Inici
      - href: seminarios.qmd
        text: Seminaris
      - href: about.qmd
        text: Sobre nosaltres
    right:
      - text: "üåê CA"
        menu:
          - text: "Catal√†"
            href: ../ca/index.html
          - text: "Castellano"
            href: ../es/index.html
          - text: "English"
            href: ../en/index.html
  page-footer:
    center: "Seminari Matem√†tiques UB - Universitat de Barcelona"
