project:
  type: website
  resources:
    - "seminarios/**/*.pdf"
    - "seminarios/**/*.tex"

# Perfiles de idioma (es, ca, en)
profile:
  group:
    - [es, ca, en]
  default: es

# Archivo de variables de configuraci√≥n
metadata-files:
  - _variables.yml

website:
  description: "{{< var seminario.descripcion >}}"
  repo-url: "https://github.com/CarlosFerLo/seminario-de-estudiantes-matematicas-ub"
  repo-branch: main
  repo-actions: [issue, source]
  navbar:
    background: primary

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3

execute:
  freeze: auto
  enabled: true



